name: Build Cryptlex.LexActivator package

on:
  workflow_dispatch:
    inputs:
      libaray version:
        description: 'library version'
        required: true
        default: ''
      package version:
        description: 'package version'
        required: true
        default: ''

jobs:
  update-version-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      
      - name: update xml file
        run: |
          sudo snap install xmlstarlet 
          xmlstarlet ed -L -u /project/version -v "${{ github.event.inputs.version }}" Cryptlex.LexActivator.nuspec    
      
      - name: update text file
        run: |
          sed -i '/lexactivator_version =/!b;c$lexactivator_version ="${{ github.event.inputs.version }}"' post-build.ps1

jobs:
  build-publish:

    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        nuget-version: '5.x'
      
    - name: Restore NuGet Packages
      run: nuget restore Cryptlex.LexActivator.sln
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    
    - name: Build Solution
      run: msbuild Cryptlex.LexActivator.sln /p:platform="Any CPU" /p:configuration="Release" /p:VisualStudioVersion="16.0"
    
    - name: Download Native Libs
      run: .\post-build.ps1
      shell: powershell
      
    - name: Pack NuGet Package
      run: nuget pack src\Cryptlex.LexActivator\Cryptlex.LexActivator.nuspec -NonInteractive -OutputDirectory nupkg -Properties Configuration=Release -Verbosity Detailed
    
    - name: Push NuGet Package
      run: nuget push nupkg\*.nupkg -SkipDuplicate -Source https://api.nuget.org/v3/index.json -NoSymbols

